name: UI Tests (Selenium)

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'
      - name: Ejecutar UI tests (headless)
        run: mvn -q -DbaseUrl=${{ env.BASE_URL || 'http://localhost:8080' }} -Dnavegador=chrome -Dheadless=true clean test
      - name: Subir Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: "**/allure-results"
      - name: Subir screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: selenium-screenshots
          path: "target/selenium-screenshots"

